# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: acd823b690693c924bcc8d74591c1a03fa2578166f049fa8e0de23360c8bbc25f987518d025f77b83a30887478353b1068e8544e15e46828506d5d8b7b0bebd6

test:
  secret_key_base: 281eb213b753b25adec7a3b4af603f7a8a93c67bf6247dd87892b2e8c8ee000c7904f16a223b85fcd0a815386e1a02f754d814d503802c2bd1bb40ee4a033741

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
